extends "res://tests/test_base.gd"

# Plays the prologue: the drive, the shop (both phone routes and both doors)
# and the first night (with and without feeding the dog).

func run() -> void:
	await _drive()
	await _missing_document()
	await _shop(true, "Knock")
	await _shop(false, "Push it open")
	await _night(true)
	await _night(false)

func _drive() -> void:
	section("The drive")
	gs.reset()
	var drive: Node = await open_scene("res://scenes/drive.tscn")
	var column: Node = drive.get_node("Narrator")
	var hotspots: Node = drive.get_node("%Hotspots")
	check(hotspots.spot_ids() == ["car_radio", "car_glovebox", "car_mirror", "car_passenger", "car_coat", "car_wheel"], "the car's hotspots are laid over the picture")
	check(not hotspots.interactive and not hotspots.get_spot("car_wheel").visible, "nothing can be clicked while the opening text plays; the wheel waits")
	var radio: Control = hotspots.get_spot("car_radio")
	check(radio.size.x > 50 and radio.position.x > drive.size.x * 0.4, "the radio's hotspot sits on the dashboard")
	check(gs.clock_text() == "10:40 PM", "the clock starts at 10:40 PM")
	drive.click("car_radio")
	check(column._section == "main", "a click during the opening text does nothing")
	advance(column)
	check(hotspots.interactive, "once it's over, the car can be clicked")

	drive.click("car_glovebox")
	check(not hotspots.interactive, "the car stops reacting while the story talks")
	var latch: Array = column.get_children().filter(func(n: Node) -> bool: return n is AudioStreamPlayer and n.stream == Sfx.stream("latch"))
	check(latch.size() == 1 and latch[0].playing, "the glovebox latch clicks (a sound made in code)")
	advance(column)
	await wait(0.7)
	check(drive.current_view() == "glovebox" and hotspots.interactive, "the glovebox opens into a close-up")
	check(hotspots.spot_ids() == ["glove_napkins", "glove_gauge", "glove_ticket", "glove_papers", "glove_close"], "napkins, the tire gauge, the ticket, the papers, and closing it")
	drive.click("glove_napkins")
	advance(column)
	check(hotspots.interactive and hotspots.get_spot("glove_napkins").used, "the napkins, then back to the glovebox")
	drive.click("glove_ticket")
	advance(column)
	check(gs.has_item("pawn_ticket"), "the ticket goes in your pockets")
	drive.click("glove_papers")
	advance(column)
	var viewer: Node = drive.get_node("%DocumentViewer")
	check(viewer.visible and gs.has_item("rental_agreement"), "the papers are the rental agreement: it opens, and goes in your pockets")
	viewer.get_node("%Backdrop").gui_input.emit(_mouse_down())
	check(not viewer.visible and hotspots.interactive, "a click outside the page puts it away, back to the glovebox")
	drive.click("glove_close")
	advance(column)
	await wait(0.7)
	check(drive.current_view() == "car" and hotspots.interactive, "closing it, back in the car")
	check(hotspots.get_spot("car_glovebox").used, "the glovebox is done once the ticket is taken")

	drive.click("car_coat")
	check(drive.sounds["paper"].playing, "clicking the coat pocket plays the paper, right away")
	advance(column)
	await process_frame
	check(choices(column) == ["Take it out", "Leave it"], "the coat pocket offers Take it out / Leave it")
	await press_key(KEY_2)
	check(column._section == "coat_left", "pressing 2 picks the second choice")
	check(gs.voices["paranoia"] == 4, "leaving the job offer feeds Paranoia")
	advance(column)

	drive.click("car_passenger")
	advance(column)
	await process_frame
	check(choices(column) == ["Count the bullets", "Leave it wrapped"], "the passenger seat offers counting the bullets")
	await pick(column, "Count the bullets")
	check(column._section == "passenger_count", "counting the bullets plays its scene")
	advance(column)

	check(hotspots.get_spot("car_wheel").visible, "the wheel appears once enough things are looked at (glovebox, coat, passenger seat)")

	drive.click("car_mirror")
	await wait(0.7)
	var mirror: Node = drive.get_node("%MirrorArt")
	check(drive.current_view() == "mirror" and mirror.visible and mirror.lights == 1.0, "the mirror opens into a close-up, the headlights behind you in it")
	check(hotspots.spot_ids() == ["mirror_eyes", "mirror_back"], "your eyes, and back to the road")
	advance(column)
	await wait(0.5)
	check(mirror.lights == 0.0, "the headlights go out")
	check(hotspots.interactive, "then the mirror can be clicked")
	drive.click("mirror_eyes")
	advance(column)
	check(_log(column).contains("Just the eyes") and hotspots.interactive, "your own eyes in the glass")

	var hud: Node = root.get_node("Hud")
	hud.open_pockets()
	hud._select("rental_agreement")
	hud.use_button.pressed.emit()
	check(not hud.pockets_panel.visible and hud.held_item == "rental_agreement" and hud.held_label.visible, "Use it on something: the pockets close, the rental agreement in your hand")
	hotspots._on_clicked("mirror_eyes")
	check(column._section == "use_rental_eyes" and hud.held_item == "", "using it on your eyes, even looked at already, plays its own scene; your hand is empty again")
	advance(column)
	check(hotspots.interactive, "then back to the mirror")
	hud.hold("key")
	hotspots._on_clicked("mirror_eyes")
	check(column._section == "use_nothing", "something with no use there gets Paranoia's shrug")
	advance(column)
	hud.hold("key")
	var right_click: InputEventMouseButton = InputEventMouseButton.new()
	right_click.button_index = MOUSE_BUTTON_RIGHT
	right_click.pressed = true
	hud._input(right_click)
	check(hud.held_item == "" and not hud.held_label.visible, "a right-click puts it back")
	drive.click("mirror_back")
	await wait(0.7)
	check(drive.current_view() == "car" and hotspots.interactive and hotspots.get_spot("car_mirror").used, "back to the road; the mirror is done")
	drive.click("car_mirror")
	check(drive.current_view() == "car", "a used hotspot doesn't play again")
	hotspots._on_clicked("car_mirror")
	check(column._section == "seen_car_mirror", "clicking it gets a short reply of its own instead")
	advance(column)
	hotspots._on_clicked("car_coat")
	check(column._section.begins_with("seen_") and column._section != "seen_car_mirror", "anything else looked at gets one of the shared replies")
	advance(column)
	check(hotspots.interactive, "and the car wakes again")
	var others: int = gs.voices["john"] + gs.voices["appraisal"] + gs.voices["warmth"] + gs.voices["animal"]
	check(others == 0, "the prologue feeds no voice but Paranoia")

func _missing_document() -> void:
	section("A missing document doesn't freeze the game")
	var drive: Node = await open_scene("res://scenes/drive.tscn")
	var column: Node = drive.get_node("Narrator")
	drive._on_choice_made({"target": "@read_no_such_paper"})
	await process_frame
	await process_frame
	check(column._input_enabled, "the story carries on when a paper can't be found")

func _shop(pick_up: bool, door: String) -> void:
	section("The shop: " + ("picks up, knocks" if pick_up else "lets it ring, wanders first, pushes the door"))
	gs.reset()
	var shop: Node = await open_scene("res://scenes/shop.tscn")
	var column: Node = shop.get_node("%Narrator")
	var hotspots: Node = shop.get_node("%Hotspots")
	advance(column)
	await process_frame
	check(shop.current_room() == "floor" and hotspots.interactive, "you come in on the shop floor, and can move once the text is done")
	check(hotspots.spot_ids() == ["n_floor_counter", "n_floor_bear", "n_floor_furs", "n_floor_door_early"], "an arrow to the counter, the bear, the furs, the door behind you")
	shop.click("n_floor_counter")
	check(shop.sounds["floorboards"].playing, "walking plays the floorboards, on the click")
	await wait(0.8)
	check(shop.current_room() == "counter" and column._section == "at_counter", "at the counter, the phone")
	advance(column)
	check(choices(column) == ["Pick up", "Let it ring"], "the phone rings: Pick up / Let it ring")
	if pick_up:
		await pick(column, "Pick up")
		check(gs.answered_phone and gs.rules_broken.has("phone"), "picking up breaks rule four")
		await wait(shop._length_of("pickup") + 0.2)
		advance(column)
		check(shop.get_node("%DeadLine").playing, "after the breathing, the line goes dead: the tone plays")
		await pick(column, "Hang up")
		check(not shop.get_node("%DeadLine").playing, "hanging up stops it")
	else:
		await pick(column, "Let it ring")
		check(not gs.answered_phone and gs.rules_broken.is_empty(), "letting it ring breaks no rule")
	advance(column)
	await process_frame
	check(gs.flags.has("office_noticed") and hotspots.interactive, "then you notice the light under the office door, and can move")
	check(hotspots.spot_ids().has("n_counter_office_first") and hotspots.spot_ids().has("n_counter_hall"), "the office door and the hallway are there now")
	if not pick_up:
		shop.walk("hallway")
		await wait(0.8)
		shop.click("n_hall_stairs_early")
		advance(column)
		check(_log(column).contains("Not yet"), "the stairs send you back to the office")
		await process_frame
		shop.click("n_hall_back")
		await wait(0.8)
	shop.click("n_counter_office_first")
	advance(column)
	check(choices(column) == ["Knock", "Push it open"], "the office door: Knock / Push it open")
	await pick(column, door)
	advance(column)
	advance(column)
	await wait(0.8)
	check(shop.current_room() == "office" and hotspots.spot_ids().has("n_office_envelope"), door + " leads into the office, and the envelope on the desk")
	shop.click("n_office_envelope")
	advance(column)
	await pick(column, "Open it")
	await wait(shop._length_of("tear") + 0.3)
	var viewer: Node = shop.get_node("%DocumentViewer")
	check(viewer.visible and gs.has_item("letter"), "the letter opens and goes in your pockets")
	check(viewer.get_node("%BodyLabel").text.begins_with("If you're reading this"), "the letter starts as the story bible says")
	viewer._on_close_pressed()
	var reaction: String = "after_letter_answered" if pick_up else "after_letter_ignored"
	check(column._section == reaction, "putting it away plays " + reaction)
	advance(column)
	await process_frame
	check(gs.flags.has("letter_read") and hotspots.interactive and not hotspots.spot_ids().has("n_office_envelope"), "then you can move again; the envelope's gone")
	shop.click("n_office_back")
	await wait(0.8)
	shop.walk("hallway")
	await wait(0.8)
	check(hotspots.spot_ids().has("n_hall_stairs"), "now the stairs go up")
	shop.click("n_hall_stairs")
	advance(column)
	await wait(2.3)
	check(current_scene.name == "Apartment", "going upstairs leads to the apartment")

func _log(column: Node) -> String:
	var text: String = ""
	for entry in column.get_node("%Log").get_children():
		text += entry.get_parsed_text() + "\n"
	return text

func _night(feed: bool) -> void:
	section("The first night: " + ("feeds the dog" if feed else "doesn't feed the dog"))
	gs.reset()
	gs.break_rule("phone")
	var apartment: Node = await open_scene("res://scenes/apartment.tscn", 1.7)
	var column: Node = apartment.get_node("%Narrator")
	var hotspots: Node = apartment.get_node("%Hotspots")
	advance(column)
	advance(column)
	await process_frame
	check(apartment.current_room() == "main" and hotspots.interactive, "you arrive in the main room, and can move")
	check(hotspots.spot_ids() == ["a_window", "a_tv", "a_radio", "a_kitchen", "a_calendar", "a_coat", "a_to_hall"], "the windows, TV, radio, kitchen, calendar, coat, and the way to the hall")
	apartment.click("a_kitchen")
	advance(column)
	await pick(column, "Fill the bowl" if feed else "Leave it")
	advance(column)
	check(gs.fed_dog == feed, "the dog bowl choice is remembered")
	apartment.walk("hall")
	await wait(0.7)
	apartment.walk("bedroom")
	await wait(0.7)
	apartment.click("r_bed_early")
	advance(column)
	check(_log(column).contains("Not yet. The rules first."), "the bed waits for the rules")
	await process_frame
	apartment.walk("main")
	await wait(0.7)
	apartment.click("a_window")
	advance(column)
	await pick(column, "Close it")
	advance(column)
	apartment.click("a_radio")
	advance(column)
	await pick(column, "Turn it on")
	advance(column)
	check(apartment.get_node("%RadioNight").playing, "the radio plays")
	apartment.walk("bedroom")
	await wait(0.7)
	check(hotspots.spot_ids().has("r_bed") and not hotspots.spot_ids().has("r_bed_early"), "after the window and the radio, the bed is ready")
	apartment.click("r_bed")
	var route: Array = [column._section]
	for i in 40:
		column._on_advance_pressed()
		if route[-1] != column._section:
			route.append(column._section)
	var expected: Array = ["sleep", "sleep_end", "wake_bed"] if feed else ["sleep", "scratching", "sleep_end", "wake_standing"]
	check(route == expected, "the night goes " + " > ".join(expected))
	await wait(3.3)
	check(current_scene.name == "Counter" and gs.day == 1, "morning comes: day one at the counter")

func _mouse_down() -> InputEventMouseButton:
	var event: InputEventMouseButton = InputEventMouseButton.new()
	event.button_index = MOUSE_BUTTON_LEFT
	event.pressed = true
	return event
